"""base schema

Revision ID: d2be2d58bd64
Revises: 
Create Date: 2026-09-07 03:12:56.737827+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2be2d58bd64'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secrets',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('variables',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'scope', name='uq_variable_key_scope')
    )
    op.create_table('workflows',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DISABLED', 'ARCHIVED', name='workflowstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_status'), 'workflows', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('jobs',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='jobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'SCHEDULED', 'API', name='triggertype', native_enum=False, length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_wf_created', 'jobs', ['workflow_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_workflow_id'), 'jobs', ['workflow_id'], unique=False)
    op.create_table('notebooks',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebooks_created_by'), 'notebooks', ['created_by'], unique=False)
    op.create_table('schedules',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('cron', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_enabled'), 'schedules', ['enabled'], unique=False)
    op.create_index(op.f('ix_schedules_workflow_id'), 'schedules', ['workflow_id'], unique=False)
    op.create_table('notebook_versions',
    sa.Column('notebook_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notebook_id', 'version_number', name='uq_notebook_version')
    )
    op.create_index(op.f('ix_notebook_versions_notebook_id'), 'notebook_versions', ['notebook_id'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('NOTEBOOK', 'PYTHON', name='tasktype', native_enum=False, length=20), nullable=False),
    sa.Column('notebook_id', sa.Uuid(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeout_s', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_tasks_notebook_id'), 'workflow_tasks', ['notebook_id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_workflow_id'), 'workflow_tasks', ['workflow_id'], unique=False)
    op.create_table('executions',
    sa.Column('notebook_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', 'TIMEOUT', name='executionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_notebook_path', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_version_id'], ['notebook_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_executions_heartbeat', 'executions', ['status', 'last_heartbeat'], unique=False)
    op.create_index(op.f('ix_executions_notebook_version_id'), 'executions', ['notebook_version_id'], unique=False)
    op.create_index('ix_executions_status_created', 'executions', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_executions_worker_id'), 'executions', ['worker_id'], unique=False)
    op.create_table('workflow_dependencies',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('from_task_id', sa.Uuid(), nullable=False),
    sa.Column('to_task_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['from_task_id'], ['workflow_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_task_id'], ['workflow_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'from_task_id', 'to_task_id', name='uq_workflow_edge')
    )
    op.create_index(op.f('ix_workflow_dependencies_from_task_id'), 'workflow_dependencies', ['from_task_id'], unique=False)
    op.create_index(op.f('ix_workflow_dependencies_to_task_id'), 'workflow_dependencies', ['to_task_id'], unique=False)
    op.create_index(op.f('ix_workflow_dependencies_workflow_id'), 'workflow_dependencies', ['workflow_id'], unique=False)
    op.create_table('execution_logs',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='loglevel', native_enum=False, length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_logs_exec_seq', 'execution_logs', ['execution_id', 'seq'], unique=False)
    op.create_table('job_tasks',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_task_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', 'SKIPPED', name='jobtaskstatus', native_enum=False, length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_task_id'], ['workflow_tasks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_tasks_execution_id'), 'job_tasks', ['execution_id'], unique=False)
    op.create_index('ix_job_tasks_job_status', 'job_tasks', ['job_id', 'status'], unique=False)
    op.create_index(op.f('ix_job_tasks_workflow_task_id'), 'job_tasks', ['workflow_task_id'], unique=False)
    op.create_table('job_logs',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('job_task_id', sa.Uuid(), nullable=True),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='loglevel', native_enum=False, length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_task_id'], ['job_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_logs_job_seq', 'job_logs', ['job_id', 'seq'], unique=False)
    op.create_index(op.f('ix_job_logs_job_task_id'), 'job_logs', ['job_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_logs_job_task_id'), table_name='job_logs')
    op.drop_index('ix_job_logs_job_seq', table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index(op.f('ix_job_tasks_workflow_task_id'), table_name='job_tasks')
    op.drop_index('ix_job_tasks_job_status', table_name='job_tasks')
    op.drop_index(op.f('ix_job_tasks_execution_id'), table_name='job_tasks')
    op.drop_table('job_tasks')
    op.drop_index('ix_execution_logs_exec_seq', table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index(op.f('ix_workflow_dependencies_workflow_id'), table_name='workflow_dependencies')
    op.drop_index(op.f('ix_workflow_dependencies_to_task_id'), table_name='workflow_dependencies')
    op.drop_index(op.f('ix_workflow_dependencies_from_task_id'), table_name='workflow_dependencies')
    op.drop_table('workflow_dependencies')
    op.drop_index(op.f('ix_executions_worker_id'), table_name='executions')
    op.drop_index('ix_executions_status_created', table_name='executions')
    op.drop_index(op.f('ix_executions_notebook_version_id'), table_name='executions')
    op.drop_index('ix_executions_heartbeat', table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_workflow_tasks_workflow_id'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_notebook_id'), table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_index(op.f('ix_notebook_versions_notebook_id'), table_name='notebook_versions')
    op.drop_table('notebook_versions')
    op.drop_index(op.f('ix_schedules_workflow_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_enabled'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_notebooks_created_by'), table_name='notebooks')
    op.drop_table('notebooks')
    op.drop_index(op.f('ix_jobs_workflow_id'), table_name='jobs')
    op.drop_index('ix_jobs_wf_created', table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_audit_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_workflows_status'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_table('variables')
    op.drop_table('users')
    op.drop_table('secrets')
    # ### end Alembic commands ###
