"""execution output notebook

Revision ID: 61c8d74f8b87
Revises: d2be2d58bd64
Create Date: 2026-09-07 03:17:47.652298+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61c8d74f8b87'
down_revision: str | None = 'd2be2d58bd64'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('output_notebook', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'output_notebook')
    # ### end Alembic commands ###
