"""workflow task ui_position

Revision ID: e17eedf8dd7f
Revises: 61c8d74f8b87
Create Date: 2026-09-07 04:02:35.767504+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e17eedf8dd7f'
down_revision: str | None = '61c8d74f8b87'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_tasks', sa.Column('ui_position', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_tasks', 'ui_position')
    # ### end Alembic commands ###
