"""execution retry_policy and timeout override

Revision ID: 7d302da88f33
Revises: e17eedf8dd7f
Create Date: 2026-09-07 04:14:00.380091+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d302da88f33'
down_revision: str | None = 'e17eedf8dd7f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('retry_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('executions', sa.Column('timeout_s', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'timeout_s')
    op.drop_column('executions', 'retry_policy')
    # ### end Alembic commands ###
