"""notifications

Revision ID: 1e9e8ef98ecd
Revises: 1d9e3f05807c
Create Date: 2026-09-07 15:45:15.972971+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e9e8ef98ecd'
down_revision: str | None = '1d9e3f05807c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password_ct', sa.Text(), nullable=True),
    sa.Column('smtp_from', sa.String(length=320), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('bitrix_enabled', sa.Boolean(), nullable=False),
    sa.Column('bitrix_url', sa.String(length=500), nullable=True),
    sa.Column('bitrix_send_message_path', sa.String(length=255), nullable=True),
    sa.Column('bitrix_bot_id', sa.String(length=120), nullable=True),
    sa.Column('bitrix_bot_token_ct', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_configs',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('on_failure', sa.Boolean(), nullable=False),
    sa.Column('on_success', sa.Boolean(), nullable=False),
    sa.Column('on_retry', sa.Boolean(), nullable=False),
    sa.Column('on_cancelled', sa.Boolean(), nullable=False),
    sa.Column('on_started', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('email_cc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('email_bcc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('email_subject', sa.String(length=300), nullable=True),
    sa.Column('bitrix_enabled', sa.Boolean(), nullable=False),
    sa.Column('bitrix_dialog_id', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id')
    )
    op.create_table('notifications',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=True),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'BITRIX', name='notificationchannel', native_enum=False, length=20), nullable=False),
    sa.Column('event_type', sa.Enum('JOB_FAILED', 'JOB_SUCCESS', 'JOB_RETRY', 'JOB_CANCELLED', 'JOB_STARTED', name='notificationevent', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENDING', 'SENT', 'FAILED', name='notificationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('recipient', sa.String(length=500), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'event_type', 'channel', name='uq_notification_idempotency')
    )
    op.create_index(op.f('ix_notifications_job_id'), 'notifications', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_job_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_configs')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
