"""notification default on failure

Revision ID: 10ff2ca0360d
Revises: 1e9e8ef98ecd
Create Date: 2026-09-07 20:00:05.571853+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10ff2ca0360d'
down_revision: str | None = '1e9e8ef98ecd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'notification_settings',
        sa.Column(
            'default_on_failure', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        'notification_settings',
        sa.Column(
            'default_email_recipients',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column(
        'notification_settings',
        sa.Column('default_bitrix_dialog_id', sa.String(length=120), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_settings', 'default_bitrix_dialog_id')
    op.drop_column('notification_settings', 'default_email_recipients')
    op.drop_column('notification_settings', 'default_on_failure')
    # ### end Alembic commands ###
