/**
 * Ícones da aplicação (lucide-react). Nomes semânticos → mapeados para o
 * equivalente Material mais próximo. NUNCA usar emojis na interface.
 */
export {
  LayoutDashboard as DashboardIcon,
  BookOpen as NotebookIcon,
  Workflow as WorkflowIcon,
  GitBranch as PipelineIcon,
  CalendarDays as ScheduleIcon,
  History as HistoryIcon,
  Terminal as LogsIcon,
  Settings as SettingsIcon,
  KeyRound as SecretIcon,
  Variable as VariableIcon,
  ListChecks as JobsIcon,
  // ações
  Plus as AddIcon,
  Pencil as EditIcon,
  Trash2 as DeleteIcon,
  Play as RunIcon,
  Square as StopIcon,
  Pause as PauseIcon,
  Eye as ViewIcon,
  FileText as DescriptionIcon,
  RotateCcw as RetryIcon,
  Download as DownloadIcon,
  Copy as DuplicateIcon,
  MoreVertical as MoreIcon,
  Save as SaveIcon,
  Search as SearchIcon,
  X as CloseIcon,
  Check as CheckIcon,
  AlertTriangle as WarnIcon,
  Info as InfoIcon,
  RefreshCw as RefreshIcon,
  ChevronLeft as BackIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  PanelLeftClose as CollapseIcon,
  PanelLeft as ExpandIcon,
  Menu as MenuIcon,
  LogOut as LogoutIcon,
  Loader2 as SpinnerIcon,
  CircleCheck as SuccessIcon,
  CircleX as FailIcon,
  Circle as QueuedIcon,
  CircleDot as RunningIcon,
  CircleSlash as CancelledIcon,
  Timer as TimeoutIcon,
  MoveRight as SkippedIcon,
} from "lucide-react";
